"""
Lalka Knowledge Graph — data inspection

Inspects JSON files generated by extract_lalka.py.

The script does not modify any data.
It produces a human-readable report in the terminal.
"""

from pathlib import Path
import json
from collections import Counter

import pandas as pd


# =============================================================================
# CONFIGURATION
# =============================================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"


FILES = {
    "records": DATA_DIR / "lalka_records_raw.json",
    "authors": DATA_DIR / "lalka_authors_raw.json",
    "creators": DATA_DIR / "lalka_creators_raw.json",
    "publishers": DATA_DIR / "lalka_publishers_raw.json",
    "metadata": DATA_DIR / "lalka_extraction_metadata.json",
}


# =============================================================================
# HELPERS
# =============================================================================

def load_json(path):
    """Load JSON file using UTF-8."""
    with open(path, "r", encoding="utf-8") as file:
        return json.load(file)


def print_separator(char="=", length=80):
    print(char * length)


def print_header(title):
    print()
    print_separator()
    print(title)
    print_separator()


def print_subheader(title):
    print()
    print(f"--- {title} ---")


def safe_str(value):
    """Return a readable string for None / NaN values."""
    if value is None:
        return ""

    if pd.isna(value):
        return ""

    return str(value).strip()


def show_dataframe(df, columns=None, max_rows=20):
    """Print selected dataframe columns."""
    if df.empty:
        print("  No records found.")
        return

    if columns:
        available = [c for c in columns if c in df.columns]
        df = df[available]

    print(df.head(max_rows).to_string(index=False))

    if len(df) > max_rows:
        print(f"\n  ... showing first {max_rows} of {len(df)} records")


def find_person_rows(df, first_name=None, last_name=None):
    """
    Search for a person in both author and creator columns.

    Returns records containing the person as author OR creator.
    """

    conditions = []

    if "AM_IMIE" in df.columns and "AM_NAZWISKO" in df.columns:
        author_condition = pd.Series(True, index=df.index)

        if first_name:
            author_condition &= (
                df["AM_IMIE"]
                .fillna("")
                .astype(str)
                .str.contains(first_name, case=False, na=False)
            )

        if last_name:
            author_condition &= (
                df["AM_NAZWISKO"]
                .fillna("")
                .astype(str)
                .str.contains(last_name, case=False, na=False)
            )

        conditions.append(author_condition)

    if "TW_IMIE" in df.columns and "TW_NAZWISKO" in df.columns:
        creator_condition = pd.Series(True, index=df.index)

        if first_name:
            creator_condition &= (
                df["TW_IMIE"]
                .fillna("")
                .astype(str)
                .str.contains(first_name, case=False, na=False)
            )

        if last_name:
            creator_condition &= (
                df["TW_NAZWISKO"]
                .fillna("")
                .astype(str)
                .str.contains(last_name, case=False, na=False)
            )

        conditions.append(creator_condition)

    if not conditions:
        return df.iloc[0:0]

    combined = conditions[0]

    for condition in conditions[1:]:
        combined |= condition

    return df[combined].drop_duplicates()


def find_title_rows(df, phrase):
    """Find records whose title contains the given phrase."""
    if "ZA_TYTUL" not in df.columns:
        return df.iloc[0:0]

    mask = (
        df["ZA_TYTUL"]
        .fillna("")
        .astype(str)
        .str.contains(phrase, case=False, na=False)
    )

    return df[mask].drop_duplicates()


def print_person_report(df, first_name, last_name):
    """Print all records associated with a person."""
    full_name = f"{first_name} {last_name}"

    print_subheader(full_name)

    person_df = find_person_rows(
        df,
        first_name=first_name,
        last_name=last_name,
    )

    if person_df.empty:
        print("  No records found.")
        return

    print(f"Records found: {len(person_df)}")

    columns = [
        "ZA_ZAPIS_ID",
        "ZAPIS_NADRZEDNY",
        "ZA_TYPE",
        "ZA_TYTUL",
        "DZ_NAZWA",
        "ZR_TYTUL",
        "ZA_ZRODLO_ROK",
        "AM_AUTOR_ID",
        "AM_IMIE",
        "AM_NAZWISKO",
        "TW_TWORCA_ID",
        "TW_IMIE",
        "TW_NAZWISKO",
    ]

    show_dataframe(person_df, columns=columns, max_rows=50)


def print_title_report(df, phrase):
    """Print records whose title contains phrase."""
    print_subheader(f'Title search: "{phrase}"')

    title_df = find_title_rows(df, phrase)

    if title_df.empty:
        print("  No records found.")
        return

    print(f"Records found: {len(title_df)}")

    columns = [
        "ZA_ZAPIS_ID",
        "ZAPIS_NADRZEDNY",
        "ZA_TYPE",
        "ZA_TYTUL",
        "DZ_NAZWA",
        "ZR_ZRODLO_ID",
        "ZR_TYTUL",
        "ZA_ZRODLO_ROK",
    ]

    show_dataframe(title_df, columns=columns, max_rows=50)


# =============================================================================
# MAIN RECORDS
# =============================================================================

def inspect_records():
    print_header("1. MAIN PBL RECORDS")

    path = FILES["records"]

    print(f"File: {path}")
    print(f"Exists: {path.exists()}")

    if not path.exists():
        print("ERROR: File not found.")
        return None

    records = load_json(path)

    print(f"Type: {type(records).__name__}")
    print(f"Number of objects: {len(records)}")

    if not records:
        print("No records.")
        return None

    df = pd.DataFrame(records)

    print_subheader("Structure")

    print(f"Number of records: {len(df)}")

    print("Columns:")
    for column in df.columns:
        print(f"  - {column}")

    # -------------------------------------------------------------------------
    # Missing values
    # -------------------------------------------------------------------------

    print_subheader("Missing values")

    missing = df.isna().sum()

    missing = missing[missing > 0].sort_values(ascending=False)

    if missing.empty:
        print("  No missing values.")
    else:
        for column, count in missing.items():
            percentage = count / len(df) * 100
            print(f"  - {column}: {count} ({percentage:.1f}%)")

    # -------------------------------------------------------------------------
    # Record types
    # -------------------------------------------------------------------------

    if "ZA_TYPE" in df.columns:
        print_subheader("Record types")

        counts = df["ZA_TYPE"].value_counts(dropna=False)

        for value, count in counts.items():
            print(f"{count:6} | {value}")

    # -------------------------------------------------------------------------
    # PBL sections
    # -------------------------------------------------------------------------

    if "DZ_NAZWA" in df.columns:
        print_subheader("PBL sections")

        counts = df["DZ_NAZWA"].value_counts(dropna=False)

        for value, count in counts.items():
            print(f"{count:6} | {value}")

    # -------------------------------------------------------------------------
    # Sources
    # -------------------------------------------------------------------------

    if "ZR_TYTUL" in df.columns:
        print_subheader("Sources")

        counts = df["ZR_TYTUL"].value_counts(dropna=False).head(30)

        for value, count in counts.items():
            print(f"{count:6} | {value}")

    # -------------------------------------------------------------------------
    # Years
    # -------------------------------------------------------------------------

    print_subheader("Years")

    for column in ["ZA_ZRODLO_ROK", "ZA_ROK_WYDANIA"]:
        if column not in df.columns:
            continue

        numeric = pd.to_numeric(df[column], errors="coerce").dropna()

        if numeric.empty:
            print(f"{column}: no numeric values")
            continue

        print(f"{column}:")
        print(f"  Minimum: {int(numeric.min())}")
        print(f"  Maximum: {int(numeric.max())}")
        print(f"  Unique years: {numeric.nunique()}")

    # -------------------------------------------------------------------------
    # Hierarchy
    # -------------------------------------------------------------------------

    if "ZAPIS_NADRZEDNY" in df.columns:
        print_subheader("Record hierarchy")

        with_parent = df["ZAPIS_NADRZEDNY"].notna().sum()
        without_parent = df["ZAPIS_NADRZEDNY"].isna().sum()

        print(
            f"Records with parent: "
            f"{with_parent} ({with_parent / len(df) * 100:.1f}%)"
        )

        print(
            f"Records without parent: "
            f"{without_parent} ({without_parent / len(df) * 100:.1f}%)"
        )

        parent_counts = (
            df["ZAPIS_NADRZEDNY"]
            .dropna()
            .value_counts()
            .head(20)
        )

        print()
        print("Most frequently referenced parent records:")

        for parent_id, count in parent_counts.items():
            print(f"  {int(parent_id)} -> {count} child records")

    # -------------------------------------------------------------------------
    # Sample
    # -------------------------------------------------------------------------

    print_subheader("Sample records")

    columns = [
        "ZA_ZAPIS_ID",
        "ZAPIS_NADRZEDNY",
        "ZA_TYPE",
        "ZA_TYTUL",
        "DZ_NAZWA",
        "ZR_TYTUL",
        "ZA_ZRODLO_ROK",
        "ZA_ROK_WYDANIA",
    ]

    show_dataframe(df, columns=columns, max_rows=20)

    return df


# =============================================================================
# AUTHORS
# =============================================================================

def inspect_authors():
    print_header("2. AUTHORS")

    path = FILES["authors"]

    print(f"File: {path}")
    print(f"Exists: {path.exists()}")

    if not path.exists():
        print("ERROR: File not found.")
        return None

    data = load_json(path)
    df = pd.DataFrame(data)

    print(f"Number of author relations: {len(df)}")

    if df.empty:
        return df

    print("Columns:")
    for column in df.columns:
        print(f"  - {column}")

    # -------------------------------------------------------------------------
    # Unique authors
    # -------------------------------------------------------------------------

    id_column = "AUTOR_ID"

    if id_column in df.columns:
        print_subheader("Unique authors")

        print(
            f"Unique author IDs: "
            f"{df[id_column].dropna().nunique()}"
        )

    # -------------------------------------------------------------------------
    # Most frequent authors
    # -------------------------------------------------------------------------

    if "IMIE" in df.columns and "NAZWISKO" in df.columns:

        print_subheader("Most frequent authors")

        temp = df.copy()

        temp["PERSON"] = (
            temp["IMIE"].fillna("").astype(str).str.strip()
            + " "
            + temp["NAZWISKO"].fillna("").astype(str).str.strip()
        ).str.strip()

        counts = temp["PERSON"].value_counts().head(30)

        for person, count in counts.items():
            print(f"{count:4} | {person}")

    return df


# =============================================================================
# CREATORS
# =============================================================================

def inspect_creators():
    print_header("3. CREATORS")

    path = FILES["creators"]

    print(f"File: {path}")
    print(f"Exists: {path.exists()}")

    if not path.exists():
        print("ERROR: File not found.")
        return None

    data = load_json(path)
    df = pd.DataFrame(data)

    print(f"Number of creator relations: {len(df)}")

    if df.empty:
        return df

    print("Columns:")
    for column in df.columns:
        print(f"  - {column}")

    if "TWORCA_ID" in df.columns:
        print_subheader("Unique creators")

        print(
            f"Unique creator IDs: "
            f"{df['TWORCA_ID'].dropna().nunique()}"
        )

    if "IMIE" in df.columns and "NAZWISKO" in df.columns:

        print_subheader("Most frequent creators")

        temp = df.copy()

        temp["PERSON"] = (
            temp["IMIE"].fillna("").astype(str).str.strip()
            + " "
            + temp["NAZWISKO"].fillna("").astype(str).str.strip()
        ).str.strip()

        counts = temp["PERSON"].value_counts().head(30)

        for person, count in counts.items():
            print(f"{count:4} | {person}")

    return df


# =============================================================================
# PUBLISHERS
# =============================================================================

def inspect_publishers():
    print_header("4. PUBLISHERS")

    path = FILES["publishers"]

    print(f"File: {path}")
    print(f"Exists: {path.exists()}")

    if not path.exists():
        print("ERROR: File not found.")
        return None

    data = load_json(path)
    df = pd.DataFrame(data)

    print(f"Number of publisher relations: {len(df)}")

    if df.empty:
        return df

    print("Columns:")
    for column in df.columns:
        print(f"  - {column}")

    if "WYDAWNICTWO_ID" in df.columns:
        print_subheader("Unique publishers")

        print(
            f"Unique publisher IDs: "
            f"{df['WYDAWNICTWO_ID'].dropna().nunique()}"
        )

    if "NAZWA" in df.columns:
        print_subheader("Most frequent publishers")

        counts = df["NAZWA"].value_counts().head(30)

        for publisher, count in counts.items():
            print(f"{count:4} | {publisher}")

    return df


# =============================================================================
# METADATA
# =============================================================================

def inspect_metadata():
    print_header("5. EXTRACTION METADATA")

    path = FILES["metadata"]

    print(f"File: {path}")
    print(f"Exists: {path.exists()}")

    if not path.exists():
        print("ERROR: File not found.")
        return None

    metadata = load_json(path)

    print(json.dumps(metadata, ensure_ascii=False, indent=2))

    return metadata


# =============================================================================
# PEOPLE OF INTEREST
# =============================================================================

def inspect_people_of_interest(df):
    print_header("6. PEOPLE OF INTEREST")

    people = [
        ("Bolesław", "Prus"),
        ("Tadeusz", "Kondrat"),
        ("Marek", "Kondrat"),
    ]

    for first_name, last_name in people:
        print_person_report(df, first_name, last_name)


# =============================================================================
# RECORDS OF INTEREST
# =============================================================================

def inspect_records_of_interest(df):
    print_header("7. RECORDS OF INTEREST")

    titles = [
        "Lalka",
    ]

    for title in titles:
        print_title_report(df, title)


# =============================================================================
# SCREEN ADAPTATIONS
# =============================================================================

def inspect_screen_adaptations(df):
    print_header("8. SCREEN ADAPTATIONS")

    if "DZ_NAZWA" not in df.columns:
        print("DZ_NAZWA column not found.")
        return

    screen_sections = [
        "Filmy fabularne pełnometrażowe",
        "Filmy telewizyjne",
        "Spektakle fabularne TV",
    ]

    for section in screen_sections:

        section_df = df[
            df["DZ_NAZWA"]
            .fillna("")
            .astype(str)
            .eq(section)
        ]

        print_subheader(section)

        print(f"Records: {len(section_df)}")

        columns = [
            "ZA_ZAPIS_ID",
            "ZAPIS_NADRZEDNY",
            "ZA_TYPE",
            "ZA_TYTUL",
            "ZR_TYTUL",
            "ZA_ZRODLO_ROK",
        ]

        show_dataframe(
            section_df,
            columns=columns,
            max_rows=50,
        )


# =============================================================================
# KNOWLEDGE GRAPH CANDIDATES
# =============================================================================

def inspect_kg_candidates(df, authors_df, creators_df, publishers_df):
    print_header("9. KNOWLEDGE GRAPH CANDIDATES")

    print("Potential entity types found in the extracted data:")

    entities = [
        "PBL record",
        "Literary work",
        "Film / screen adaptation",
        "Theatre / TV production",
        "Author",
        "Creator / person",
        "Publisher",
        "Source / periodical",
        "PBL section / domain",
    ]

    for entity in entities:
        print(f"  - {entity}")

    print()
    print("Potential relationships:")

    relationships = [
        "record -> parent record",
        "record -> author",
        "record -> creator",
        "record -> publisher",
        "record -> source",
        "record -> PBL section",
        "record -> publication year",
        "person -> record",
        "screen adaptation -> related PBL records",
    ]

    for relationship in relationships:
        print(f"  - {relationship}")

    # -------------------------------------------------------------------------
    # ID availability
    # -------------------------------------------------------------------------

    print_subheader("Identifier availability")

    if "ZA_ZAPIS_ID" in df.columns:
        print(
            f"PBL records with ID: "
            f"{df['ZA_ZAPIS_ID'].notna().sum()} / {len(df)}"
        )

    if authors_df is not None and "AUTOR_ID" in authors_df.columns:
        print(
            f"Author relations with ID: "
            f"{authors_df['AUTOR_ID'].notna().sum()} / {len(authors_df)}"
        )

    if creators_df is not None and "TWORCA_ID" in creators_df.columns:
        print(
            f"Creator relations with ID: "
            f"{creators_df['TWORCA_ID'].notna().sum()} / {len(creators_df)}"
        )

    if publishers_df is not None and "WYDAWNICTWO_ID" in publishers_df.columns:
        print(
            f"Publisher relations with ID: "
            f"{publishers_df['WYDAWNICTWO_ID'].notna().sum()} / {len(publishers_df)}"
        )


# =============================================================================
# SUMMARY
# =============================================================================

def print_summary(df, authors_df, creators_df, publishers_df):

    print_header("10. SUMMARY")

    if df is not None:
        print(f"Main records:       {len(df)}")

    if authors_df is not None:
        print(f"Author relations:   {len(authors_df)}")

    if creators_df is not None:
        print(f"Creator relations:  {len(creators_df)}")

    if publishers_df is not None:
        print(f"Publisher relations:{len(publishers_df)}")

    print()
    print("Inspection completed.")


# =============================================================================
# MAIN
# =============================================================================

def main():

    print_separator()
    print("LALKA KNOWLEDGE GRAPH — DATA INSPECTION")
    print_separator()

    print()
    print("Data directory:")
    print(DATA_DIR)

    # Main data
    records_df = inspect_records()

    # Related tables
    authors_df = inspect_authors()
    creators_df = inspect_creators()
    publishers_df = inspect_publishers()

    # Metadata
    inspect_metadata()

    # Only continue if main records exist
    if records_df is not None:

        # People
        inspect_people_of_interest(records_df)

        # Titles
        inspect_records_of_interest(records_df)

        # Screen adaptations
        inspect_screen_adaptations(records_df)

        # KG candidates
        inspect_kg_candidates(
            records_df,
            authors_df,
            creators_df,
            publishers_df,
        )

    # Summary
    print_summary(
        records_df,
        authors_df,
        creators_df,
        publishers_df,
    )


if __name__ == "__main__":
    main()