"""
Lalka Knowledge Graph — data inspection

Inspects JSON files generated by extract_lalka.py.

The script does not modify any data.
It produces a human-readable report in the terminal.

The inspection is designed to work with the exported column names
used by extract_lalka.py, rather than assuming that raw Oracle
column names are present in the JSON files.
"""

from pathlib import Path
import json

import pandas as pd


# =============================================================================
# CONFIGURATION
# =============================================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"


FILES = {
    "records": DATA_DIR / "lalka_records_raw.json",
    "authors": DATA_DIR / "lalka_authors_raw.json",
    "creators": DATA_DIR / "lalka_creators_raw.json",
    "publishers": DATA_DIR / "lalka_publishers_raw.json",
    "metadata": DATA_DIR / "lalka_extraction_metadata.json",
}


# =============================================================================
# HELPERS
# =============================================================================

def load_json(path):
    """Load JSON file using UTF-8."""

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as file:
        return json.load(file)


def print_separator(
    char="=",
    length=80,
):
    print(char * length)


def print_header(title):
    print()
    print_separator()
    print(title)
    print_separator()


def print_subheader(title):
    print()
    print(f"--- {title} ---")


def show_dataframe(
    df,
    columns=None,
    max_rows=20,
):
    """
    Print selected dataframe columns.

    Missing columns are silently ignored.
    This prevents the inspection script from crashing
    when the exported structure changes.
    """

    if df is None or df.empty:
        print("  No records found.")
        return

    if columns:
        available = [
            column
            for column in columns
            if column in df.columns
        ]

        if not available:
            print("  No requested columns available.")
            return

        df = df[available]

    print(
        df.head(max_rows).to_string(
            index=False
        )
    )

    if len(df) > max_rows:
        print(
            f"\n  ... showing first "
            f"{max_rows} of {len(df)} records"
        )


def contains_text(
    series,
    phrase,
):
    """
    Case-insensitive text search.
    """

    return (
        series
        .fillna("")
        .astype(str)
        .str.contains(
            phrase,
            case=False,
            na=False,
            regex=False,
        )
    )


# =============================================================================
# PERSON SEARCH
# =============================================================================

def find_person_rows(
    df,
    first_name=None,
    last_name=None,
):
    """
    Search for a person in author and creator relations.

    This function is kept for compatibility with older exports.
    The current records JSON does not contain author / creator
    names directly, so person reports are performed separately
    using authors_df and creators_df.
    """

    if df is None or df.empty:
        return df.iloc[0:0] if df is not None else pd.DataFrame()

    conditions = []

    # -------------------------------------------------------------------------
    # Authors
    # -------------------------------------------------------------------------

    if (
        "IMIE" in df.columns
        and "NAZWISKO" in df.columns
    ):

        condition = pd.Series(
            True,
            index=df.index,
        )

        if first_name:
            condition &= contains_text(
                df["IMIE"],
                first_name,
            )

        if last_name:
            condition &= contains_text(
                df["NAZWISKO"],
                last_name,
            )

        conditions.append(condition)

    # -------------------------------------------------------------------------
    # Creators
    # -------------------------------------------------------------------------

    if (
        "TW_IMIE" in df.columns
        and "TW_NAZWISKO" in df.columns
    ):

        condition = pd.Series(
            True,
            index=df.index,
        )

        if first_name:
            condition &= contains_text(
                df["TW_IMIE"],
                first_name,
            )

        if last_name:
            condition &= contains_text(
                df["TW_NAZWISKO"],
                last_name,
            )

        conditions.append(condition)

    if not conditions:
        return df.iloc[0:0]

    combined = conditions[0]

    for condition in conditions[1:]:
        combined |= condition

    return df[combined].drop_duplicates()


# =============================================================================
# TITLE SEARCH
# =============================================================================

def find_title_rows(
    df,
    phrase,
):
    """
    Find records whose title contains the given phrase.
    """

    if (
        df is None
        or df.empty
        or "ZA_TYTUL" not in df.columns
    ):
        return (
            df.iloc[0:0]
            if df is not None
            else pd.DataFrame()
        )

    mask = contains_text(
        df["ZA_TYTUL"],
        phrase,
    )

    return df[mask].drop_duplicates()


def print_title_report(
    df,
    phrase,
):
    """
    Print records whose title contains phrase.
    """

    print_subheader(
        f'Title search: "{phrase}"'
    )

    title_df = find_title_rows(
        df,
        phrase,
    )

    if title_df.empty:
        print("  No records found.")
        return

    print(
        f"Records found: "
        f"{len(title_df)}"
    )

    columns = [
        "ZA_ZAPIS_ID",
        "ZAPIS_NADRZEDNY",
        "ZA_TYPE",
        "ZA_RZ_RODZAJ1_ID",
        "RZ_NAZWA",
        "ZA_TYTUL",
        "DZ_DZIAL_ID",
        "DZ_NAZWA",
        "ZR_ZRODLO_ID",
        "ZR_TYTUL",
        "ZA_ZRODLO_ROK",
        "ZA_ROK_WYDANIA",
    ]

    show_dataframe(
        title_df,
        columns=columns,
        max_rows=50,
    )


# =============================================================================
# PERSON REPORTS
# =============================================================================

def print_author_report(
    authors_df,
    records_df,
    first_name,
    last_name,
):
    """
    Find records associated with an author.
    """

    full_name = (
        f"{first_name} {last_name}"
    )

    print_subheader(
        f"Author: {full_name}"
    )

    if (
        authors_df is None
        or authors_df.empty
    ):
        print("  No author relations available.")
        return

    if (
        "IMIE" not in authors_df.columns
        or "NAZWISKO" not in authors_df.columns
    ):
        print(
            "  Author name columns not available."
        )
        return

    mask = (
        contains_text(
            authors_df["IMIE"],
            first_name,
        )
        &
        contains_text(
            authors_df["NAZWISKO"],
            last_name,
        )
    )

    matches = authors_df[mask].drop_duplicates()

    if matches.empty:
        print("  No records found.")
        return

    print(
        f"Author relations found: "
        f"{len(matches)}"
    )

    show_dataframe(
        matches,
        columns=[
            "ZAPIS_ID",
            "AUTOR_ID",
            "IMIE",
            "NAZWISKO",
        ],
        max_rows=50,
    )

    # -------------------------------------------------------------------------
    # Join with main records
    # -------------------------------------------------------------------------

    if (
        records_df is None
        or records_df.empty
        or "ZA_ZAPIS_ID" not in records_df.columns
        or "ZAPIS_ID" not in matches.columns
    ):
        return

    record_ids = set(
        pd.to_numeric(
            matches["ZAPIS_ID"],
            errors="coerce",
        )
        .dropna()
        .astype(int)
    )

    related_records = records_df[
        pd.to_numeric(
            records_df["ZA_ZAPIS_ID"],
            errors="coerce",
        )
        .isin(record_ids)
    ]

    print()
    print(
        f"Related PBL records: "
        f"{len(related_records)}"
    )

    show_dataframe(
        related_records,
        columns=[
            "ZA_ZAPIS_ID",
            "ZAPIS_NADRZEDNY",
            "ZA_TYPE",
            "RZ_NAZWA",
            "ZA_TYTUL",
            "DZ_NAZWA",
            "ZR_TYTUL",
            "ZA_ZRODLO_ROK",
        ],
        max_rows=50,
    )


def print_creator_report(
    creators_df,
    records_df,
    first_name,
    last_name,
):
    """
    Find records associated with a creator.
    """

    full_name = (
        f"{first_name} {last_name}"
    )

    print_subheader(
        f"Creator: {full_name}"
    )

    if (
        creators_df is None
        or creators_df.empty
    ):
        print("  No creator relations available.")
        return

    if (
        "IMIE" not in creators_df.columns
        or "NAZWISKO" not in creators_df.columns
    ):
        print(
            "  Creator name columns not available."
        )
        return

    mask = (
        contains_text(
            creators_df["IMIE"],
            first_name,
        )
        &
        contains_text(
            creators_df["NAZWISKO"],
            last_name,
        )
    )

    matches = creators_df[mask].drop_duplicates()

    if matches.empty:
        print("  No records found.")
        return

    print(
        f"Creator relations found: "
        f"{len(matches)}"
    )

    show_dataframe(
        matches,
        columns=[
            "ZAPIS_ID",
            "TWORCA_ID",
            "IMIE",
            "NAZWISKO",
        ],
        max_rows=50,
    )

    if (
        records_df is None
        or records_df.empty
        or "ZA_ZAPIS_ID" not in records_df.columns
        or "ZAPIS_ID" not in matches.columns
    ):
        return

    record_ids = set(
        pd.to_numeric(
            matches["ZAPIS_ID"],
            errors="coerce",
        )
        .dropna()
        .astype(int)
    )

    related_records = records_df[
        pd.to_numeric(
            records_df["ZA_ZAPIS_ID"],
            errors="coerce",
        )
        .isin(record_ids)
    ]

    print()
    print(
        f"Related PBL records: "
        f"{len(related_records)}"
    )

    show_dataframe(
        related_records,
        columns=[
            "ZA_ZAPIS_ID",
            "ZAPIS_NADRZEDNY",
            "ZA_TYPE",
            "RZ_NAZWA",
            "ZA_TYTUL",
            "DZ_NAZWA",
            "ZR_TYTUL",
            "ZA_ZRODLO_ROK",
        ],
        max_rows=50,
    )


# =============================================================================
# MAIN RECORDS
# =============================================================================

def inspect_records():

    print_header(
        "1. MAIN PBL RECORDS"
    )

    path = FILES["records"]

    print(
        f"File: {path}"
    )

    print(
        f"Exists: {path.exists()}"
    )

    if not path.exists():
        print(
            "ERROR: File not found."
        )
        return None

    records = load_json(path)

    print(
        f"Type: {type(records).__name__}"
    )

    print(
        f"Number of objects: {len(records)}"
    )

    if not records:
        print("No records.")
        return None

    df = pd.DataFrame(records)

    print_subheader(
        "Structure"
    )

    print(
        f"Number of records: {len(df)}"
    )

    print("Columns:")

    for column in df.columns:
        print(
            f"  - {column}"
        )

    # -------------------------------------------------------------------------
    # Missing values
    # -------------------------------------------------------------------------

    print_subheader(
        "Missing values"
    )

    missing = (
        df.isna()
        .sum()
    )

    missing = missing[
        missing > 0
    ].sort_values(
        ascending=False
    )

    if missing.empty:
        print(
            "  No missing values."
        )
    else:

        for column, count in missing.items():

            percentage = (
                count
                / len(df)
                * 100
            )

            print(
                f"  - {column}: "
                f"{count} "
                f"({percentage:.1f}%)"
            )

    # -------------------------------------------------------------------------
    # Record types
    # -------------------------------------------------------------------------

    if "ZA_TYPE" in df.columns:

        print_subheader(
            "Record types"
        )

        counts = (
            df["ZA_TYPE"]
            .value_counts(
                dropna=False
            )
        )

        for value, count in counts.items():

            print(
                f"{count:6} | {value}"
            )

    # -------------------------------------------------------------------------
    # Record kinds
    # -------------------------------------------------------------------------

    if "RZ_NAZWA" in df.columns:

        print_subheader(
            "Record kinds"
        )

        counts = (
            df["RZ_NAZWA"]
            .value_counts(
                dropna=False
            )
        )

        for value, count in counts.items():

            print(
                f"{count:6} | {value}"
            )

    # -------------------------------------------------------------------------
    # PBL sections
    # -------------------------------------------------------------------------

    if "DZ_NAZWA" in df.columns:

        print_subheader(
            "PBL sections"
        )

        counts = (
            df["DZ_NAZWA"]
            .value_counts(
                dropna=False
            )
        )

        for value, count in counts.items():

            print(
                f"{count:6} | {value}"
            )

    # -------------------------------------------------------------------------
    # Sources
    # -------------------------------------------------------------------------

    if "ZR_TYTUL" in df.columns:

        print_subheader(
            "Sources"
        )

        counts = (
            df["ZR_TYTUL"]
            .value_counts(
                dropna=False
            )
            .head(30)
        )

        for value, count in counts.items():

            print(
                f"{count:6} | {value}"
            )

    # -------------------------------------------------------------------------
    # Years
    # -------------------------------------------------------------------------

    print_subheader(
        "Years"
    )

    for column in [
        "ZA_ZRODLO_ROK",
        "ZA_ROK_WYDANIA",
    ]:

        if column not in df.columns:
            continue

        numeric = (
            pd.to_numeric(
                df[column],
                errors="coerce",
            )
            .dropna()
        )

        if numeric.empty:

            print(
                f"{column}: "
                f"no numeric values"
            )

            continue

        print(
            f"{column}:"
        )

        print(
            f"  Minimum: "
            f"{int(numeric.min())}"
        )

        print(
            f"  Maximum: "
            f"{int(numeric.max())}"
        )

        print(
            f"  Unique years: "
            f"{numeric.nunique()}"
        )

    # -------------------------------------------------------------------------
    # Hierarchy
    # -------------------------------------------------------------------------

    if "ZAPIS_NADRZEDNY" in df.columns:

        print_subheader(
            "Record hierarchy"
        )

        with_parent = (
            df["ZAPIS_NADRZEDNY"]
            .notna()
            .sum()
        )

        without_parent = (
            df["ZAPIS_NADRZEDNY"]
            .isna()
            .sum()
        )

        print(
            f"Records with parent: "
            f"{with_parent} "
            f"({with_parent / len(df) * 100:.1f}%)"
        )

        print(
            f"Records without parent: "
            f"{without_parent} "
            f"({without_parent / len(df) * 100:.1f}%)"
        )

        parent_counts = (
            df["ZAPIS_NADRZEDNY"]
            .dropna()
            .value_counts()
            .head(20)
        )

        if not parent_counts.empty:

            print()
            print(
                "Most frequently referenced "
                "parent records:"
            )

            for parent_id, count in parent_counts.items():

                print(
                    f"  {int(parent_id)} "
                    f"-> {count} child records"
                )

    # -------------------------------------------------------------------------
    # Sample
    # -------------------------------------------------------------------------

    print_subheader(
        "Sample records"
    )

    show_dataframe(
        df,
        columns=[
            "ZA_ZAPIS_ID",
            "ZAPIS_NADRZEDNY",
            "ZA_TYPE",
            "ZA_RZ_RODZAJ1_ID",
            "RZ_NAZWA",
            "ZA_TYTUL",
            "DZ_DZIAL_ID",
            "DZ_NAZWA",
            "ZR_ZRODLO_ID",
            "ZR_TYTUL",
            "ZA_ZRODLO_ROK",
            "ZA_ROK_WYDANIA",
        ],
        max_rows=20,
    )

    return df


# =============================================================================
# AUTHORS
# =============================================================================

def inspect_authors():

    print_header(
        "2. AUTHORS"
    )

    path = FILES["authors"]

    print(
        f"File: {path}"
    )

    print(
        f"Exists: {path.exists()}"
    )

    if not path.exists():

        print(
            "ERROR: File not found."
        )

        return None

    data = load_json(path)

    df = pd.DataFrame(data)

    print(
        f"Number of author relations: "
        f"{len(df)}"
    )

    if df.empty:
        return df

    print("Columns:")

    for column in df.columns:
        print(
            f"  - {column}"
        )

    # -------------------------------------------------------------------------
    # Unique authors
    # -------------------------------------------------------------------------

    if "AUTOR_ID" in df.columns:

        print_subheader(
            "Unique authors"
        )

        print(
            f"Unique author IDs: "
            f"{df['AUTOR_ID'].dropna().nunique()}"
        )

    # -------------------------------------------------------------------------
    # Most frequent authors
    # -------------------------------------------------------------------------

    if (
        "IMIE" in df.columns
        and "NAZWISKO" in df.columns
    ):

        print_subheader(
            "Most frequent authors"
        )

        temp = df.copy()

        temp["PERSON"] = (
            temp["IMIE"]
            .fillna("")
            .astype(str)
            .str.strip()
            + " "
            + temp["NAZWISKO"]
            .fillna("")
            .astype(str)
            .str.strip()
        ).str.strip()

        counts = (
            temp["PERSON"]
            .value_counts()
            .head(30)
        )

        for person, count in counts.items():

            print(
                f"{count:4} | {person}"
            )

    return df


# =============================================================================
# CREATORS
# =============================================================================

def inspect_creators():

    print_header(
        "3. CREATORS"
    )

    path = FILES["creators"]

    print(
        f"File: {path}"
    )

    print(
        f"Exists: {path.exists()}"
    )

    if not path.exists():

        print(
            "ERROR: File not found."
        )

        return None

    data = load_json(path)

    df = pd.DataFrame(data)

    print(
        f"Number of creator relations: "
        f"{len(df)}"
    )

    if df.empty:
        return df

    print("Columns:")

    for column in df.columns:
        print(
            f"  - {column}"
        )

    # -------------------------------------------------------------------------
    # Unique creators
    # -------------------------------------------------------------------------

    if "TWORCA_ID" in df.columns:

        print_subheader(
            "Unique creators"
        )

        print(
            f"Unique creator IDs: "
            f"{df['TWORCA_ID'].dropna().nunique()}"
        )

    # -------------------------------------------------------------------------
    # Most frequent creators
    # -------------------------------------------------------------------------

    if (
        "IMIE" in df.columns
        and "NAZWISKO" in df.columns
    ):

        print_subheader(
            "Most frequent creators"
        )

        temp = df.copy()

        temp["PERSON"] = (
            temp["IMIE"]
            .fillna("")
            .astype(str)
            .str.strip()
            + " "
            + temp["NAZWISKO"]
            .fillna("")
            .astype(str)
            .str.strip()
        ).str.strip()

        counts = (
            temp["PERSON"]
            .value_counts()
            .head(30)
        )

        for person, count in counts.items():

            print(
                f"{count:4} | {person}"
            )

    return df


# =============================================================================
# PUBLISHERS
# =============================================================================

def inspect_publishers():

    print_header(
        "4. PUBLISHERS"
    )

    path = FILES["publishers"]

    print(
        f"File: {path}"
    )

    print(
        f"Exists: {path.exists()}"
    )

    if not path.exists():

        print(
            "ERROR: File not found."
        )

        return None

    data = load_json(path)

    df = pd.DataFrame(data)

    print(
        f"Number of publisher relations: "
        f"{len(df)}"
    )

    if df.empty:
        return df

    print("Columns:")

    for column in df.columns:

        print(
            f"  - {column}"
        )

    if "WYDAWNICTWO_ID" in df.columns:

        print_subheader(
            "Unique publishers"
        )

        print(
            f"Unique publisher IDs: "
            f"{df['WYDAWNICTWO_ID'].dropna().nunique()}"
        )

    if "NAZWA" in df.columns:

        print_subheader(
            "Most frequent publishers"
        )

        counts = (
            df["NAZWA"]
            .value_counts()
            .head(30)
        )

        for publisher, count in counts.items():

            print(
                f"{count:4} | {publisher}"
            )

    return df


# =============================================================================
# METADATA
# =============================================================================

def inspect_metadata():

    print_header(
        "5. EXTRACTION METADATA"
    )

    path = FILES["metadata"]

    print(
        f"File: {path}"
    )

    print(
        f"Exists: {path.exists()}"
    )

    if not path.exists():

        print(
            "ERROR: File not found."
        )

        return None

    metadata = load_json(path)

    print(
        json.dumps(
            metadata,
            ensure_ascii=False,
            indent=2,
        )
    )

    return metadata


# =============================================================================
# PEOPLE OF INTEREST
# =============================================================================

def inspect_people_of_interest(
    records_df,
    authors_df,
    creators_df,
):

    print_header(
        "6. PEOPLE OF INTEREST"
    )

    people = [
        ("Bolesław", "Prus"),
        ("Tadeusz", "Kondrat"),
        ("Marek", "Kondrat"),
    ]

    for first_name, last_name in people:

        print_author_report(
            authors_df,
            records_df,
            first_name,
            last_name,
        )

        print_creator_report(
            creators_df,
            records_df,
            first_name,
            last_name,
        )


# =============================================================================
# RECORDS OF INTEREST
# =============================================================================

def inspect_records_of_interest(
    df,
):

    print_header(
        "7. RECORDS OF INTEREST"
    )

    titles = [
        "Lalka",
    ]

    for title in titles:

        print_title_report(
            df,
            title,
        )


# =============================================================================
# SCREEN ADAPTATIONS
# =============================================================================

def inspect_screen_adaptations(
    df,
):

    print_header(
        "8. SCREEN ADAPTATIONS"
    )

    if df is None or df.empty:

        print(
            "No main records available."
        )

        return

    # -------------------------------------------------------------------------
    # By record kind
    # -------------------------------------------------------------------------

    if "RZ_NAZWA" in df.columns:

        print_subheader(
            "Screen adaptation record kinds"
        )

        mask = contains_text(
            df["RZ_NAZWA"],
            "film",
        )

        film_df = df[mask]

        print(
            f"Records containing "
            f"'film' in record kind: "
            f"{len(film_df)}"
        )

        show_dataframe(
            film_df,
            columns=[
                "ZA_ZAPIS_ID",
                "ZAPIS_NADRZEDNY",
                "ZA_TYPE",
                "ZA_RZ_RODZAJ1_ID",
                "RZ_NAZWA",
                "ZA_TYTUL",
                "DZ_NAZWA",
                "ZR_TYTUL",
                "ZA_ZRODLO_ROK",
            ],
            max_rows=100,
        )

    # -------------------------------------------------------------------------
    # By PBL section
    # -------------------------------------------------------------------------

    if "DZ_NAZWA" in df.columns:

        print_subheader(
            "PBL sections potentially containing screen adaptations"
        )

        sections = (
            df["DZ_NAZWA"]
            .dropna()
            .astype(str)
            .drop_duplicates()
            .sort_values()
        )

        for section in sections:

            if any(
                keyword in section.lower()
                for keyword in [
                    "film",
                    "telewiz",
                    "spektak",
                    "adapt",
                ]
            ):

                count = (
                    df["DZ_NAZWA"]
                    .eq(section)
                    .sum()
                )

                print(
                    f"{count:6} | {section}"
                )

    # -------------------------------------------------------------------------
    # Titles containing Lalka
    # -------------------------------------------------------------------------

    print_subheader(
        "Screen-adaptation candidates by title"
    )

    title_mask = contains_text(
        df["ZA_TYTUL"],
        "Lalka",
    ) if "ZA_TYTUL" in df.columns else pd.Series(
        False,
        index=df.index,
    )

    title_df = df[title_mask]

    show_dataframe(
        title_df,
        columns=[
            "ZA_ZAPIS_ID",
            "ZAPIS_NADRZEDNY",
            "ZA_TYPE",
            "RZ_NAZWA",
            "ZA_TYTUL",
            "DZ_NAZWA",
            "ZR_TYTUL",
            "ZA_ZRODLO_ROK",
        ],
        max_rows=100,
    )


# =============================================================================
# KNOWLEDGE GRAPH CANDIDATES
# =============================================================================

def inspect_kg_candidates(
    df,
    authors_df,
    creators_df,
    publishers_df,
):

    print_header(
        "9. KNOWLEDGE GRAPH CANDIDATES"
    )

    print(
        "Potential entity types found "
        "in the extracted data:"
    )

    entities = [
        "PBL record",
        "Literary work",
        "Film / screen adaptation",
        "Theatre / TV production",
        "Author",
        "Creator / person",
        "Publisher",
        "Source / periodical",
        "PBL section / domain",
    ]

    for entity in entities:

        print(
            f"  - {entity}"
        )

    print()
    print(
        "Potential relationships:"
    )

    relationships = [
        "record -> parent record",
        "record -> author",
        "record -> creator",
        "record -> publisher",
        "record -> source",
        "record -> PBL section",
        "record -> publication year",
        "person -> record",
        "screen adaptation -> related PBL records",
    ]

    for relationship in relationships:

        print(
            f"  - {relationship}"
        )

    # -------------------------------------------------------------------------
    # Identifier availability
    # -------------------------------------------------------------------------

    print_subheader(
        "Identifier availability"
    )

    if (
        df is not None
        and "ZA_ZAPIS_ID" in df.columns
    ):

        print(
            f"PBL records with ID: "
            f"{df['ZA_ZAPIS_ID'].notna().sum()} "
            f"/ {len(df)}"
        )

    if (
        authors_df is not None
        and "AUTOR_ID" in authors_df.columns
    ):

        print(
            f"Author relations with ID: "
            f"{authors_df['AUTOR_ID'].notna().sum()} "
            f"/ {len(authors_df)}"
        )

    if (
        creators_df is not None
        and "TWORCA_ID" in creators_df.columns
    ):

        print(
            f"Creator relations with ID: "
            f"{creators_df['TWORCA_ID'].notna().sum()} "
            f"/ {len(creators_df)}"
        )

    if (
        publishers_df is not None
        and "WYDAWNICTWO_ID" in publishers_df.columns
    ):

        print(
            f"Publisher relations with ID: "
            f"{publishers_df['WYDAWNICTWO_ID'].notna().sum()} "
            f"/ {len(publishers_df)}"
        )


# =============================================================================
# SUMMARY
# =============================================================================

def print_summary(
    df,
    authors_df,
    creators_df,
    publishers_df,
):

    print_header(
        "10. SUMMARY"
    )

    if df is not None:
        print(
            f"Main records:        {len(df)}"
        )

    if authors_df is not None:
        print(
            f"Author relations:    {len(authors_df)}"
        )

    if creators_df is not None:
        print(
            f"Creator relations:   {len(creators_df)}"
        )

    if publishers_df is not None:
        print(
            f"Publisher relations: {len(publishers_df)}"
        )

    print()
    print(
        "Inspection completed."
    )


# =============================================================================
# MAIN
# =============================================================================

def main():

    print_separator()

    print(
        "LALKA KNOWLEDGE GRAPH — DATA INSPECTION"
    )

    print_separator()

    print()
    print(
        "Data directory:"
    )

    print(
        DATA_DIR
    )

    # -------------------------------------------------------------------------
    # Main data
    # -------------------------------------------------------------------------

    records_df = inspect_records()

    # -------------------------------------------------------------------------
    # Related tables
    # -------------------------------------------------------------------------

    authors_df = inspect_authors()

    creators_df = inspect_creators()

    publishers_df = inspect_publishers()

    # -------------------------------------------------------------------------
    # Metadata
    # -------------------------------------------------------------------------

    inspect_metadata()

    # -------------------------------------------------------------------------
    # Continue only if main records exist
    # -------------------------------------------------------------------------

    if records_df is not None:

        # People
        inspect_people_of_interest(
            records_df,
            authors_df,
            creators_df,
        )

        # Titles
        inspect_records_of_interest(
            records_df
        )

        # Screen adaptations
        inspect_screen_adaptations(
            records_df
        )

        # KG candidates
        inspect_kg_candidates(
            records_df,
            authors_df,
            creators_df,
            publishers_df,
        )

    # -------------------------------------------------------------------------
    # Summary
    # -------------------------------------------------------------------------

    print_summary(
        records_df,
        authors_df,
        creators_df,
        publishers_df,
    )


# =============================================================================
# ENTRY POINT
# =============================================================================

if __name__ == "__main__":
    main()